function Baganator.API.GetInventoryInfo(itemLink, sameConnectedRealm, sameFaction)
  local success, key = pcall(Baganator.Utilities.GetItemKey, itemLink)
  if not success then
    error("Bad item link. Try using one generated by a call to GetItemInfo.")
    return
  end

  return Baganator.ItemSummaries:GetTooltipInfo(key, sameConnectedRealm == true, sameFaction == true)
end
